using System.IO;
using CalmSpace.Audio;
using CalmSpace.Editor;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace CalmSpace.Tests.EditMode
{
    public sealed class CategorizedAsmrAuthoringTests
    {
        [Test]
        public void GeneratedPaletteAuthorsEveryCueBankForResidentPlayback()
        {
            CalmSpaceTactileAudioBuilder.GeneratedAudioPalette palette =
                CalmSpaceTactileAudioBuilder.CreateOrUpdatePalette();
            AudioClip[][] banks =
            {
                palette.Placement,
                palette.ScrewTurn,
                palette.ScrewRelease,
                palette.CleaningCloth,
                palette.CleaningSponge,
                palette.CleaningSqueegee,
                palette.LevelComplete,
                palette.RoomReveal,
                palette.UiTap
            };

            Assert.That(banks, Has.Length.EqualTo(9));
            Assert.That(palette.Placement, Has.Length.EqualTo(6),
                "The original six material placement clips must remain.");
            foreach (AudioClip[] bank in banks)
            {
                Assert.That(bank, Is.Not.Null.And.Not.Empty);
                for (var index = 0; index < bank.Length; index++)
                {
                    AudioClip clip = bank[index];
                    Assert.That(clip, Is.Not.Null);
                    string path = AssetDatabase.GetAssetPath(clip);
                    var importer = AssetImporter.GetAtPath(path) as AudioImporter;
                    Assert.That(importer, Is.Not.Null, path);
                    Assert.That(importer.forceToMono, Is.True, path);
                    Assert.That(importer.loadInBackground, Is.False, path);
                    Assert.That(
                        importer.defaultSampleSettings.loadType,
                        Is.EqualTo(AudioClipLoadType.DecompressOnLoad), path);
                    Assert.That(
                        importer.defaultSampleSettings.preloadAudioData,
                        Is.True, path);
                    Assert.That(
                        importer.defaultSampleSettings.compressionFormat,
                        Is.EqualTo(AudioCompressionFormat.PCM), path);
                }
            }
        }

        [Test]
        public void ConfigureRepairsGeneratedCueBeforeReusingCurrentScene()
        {
            CalmSpaceProjectSetup.ConfigureProject();
            CalmSpaceTactileAudioBuilder.GeneratedAudioPalette palette =
                CalmSpaceTactileAudioBuilder.CreateOrUpdatePalette();
            string assetPath = AssetDatabase.GetAssetPath(palette.UiTap[0]);
            string filePath = Path.GetFullPath(assetPath);
            byte[] expectedBytes = File.ReadAllBytes(filePath);

            try
            {
                var importer = AssetImporter.GetAtPath(assetPath) as
                    AudioImporter;
                Assert.That(importer, Is.Not.Null);
                AudioImporterSampleSettings settings =
                    importer.defaultSampleSettings;
                settings.preloadAudioData = false;
                importer.defaultSampleSettings = settings;
                importer.SaveAndReimport();

                byte[] corruptedBytes = (byte[])expectedBytes.Clone();
                corruptedBytes[corruptedBytes.Length - 1] ^= 0x01;
                File.WriteAllBytes(filePath, corruptedBytes);

                CalmSpaceProjectSetup.ConfigureProject();

                CollectionAssert.AreEqual(
                    expectedBytes,
                    File.ReadAllBytes(filePath),
                    "Configure must repair generated bytes even when Main " +
                    "can otherwise be reused.");
                importer = AssetImporter.GetAtPath(assetPath) as AudioImporter;
                Assert.That(
                    importer.defaultSampleSettings.preloadAudioData,
                    Is.True,
                    "Configure must repair resident-playback import settings.");
            }
            finally
            {
                CalmSpaceTactileAudioBuilder.CreateOrUpdatePalette();
            }
        }
    }
}
