"""Deterministic gouache painting primitives for the Calm Space workshop art.

Everything here is original, procedurally authored output. No third-party
image, texture, or brush asset is read, downloaded, or embedded. The module is
pure numpy + Pillow so the room art can be regenerated byte-identically from
source at any time.

Coordinate space is the portrait reference composition used by the runtime
CanvasScaler: 1080 x 2400, origin at the top-left corner.
"""

from __future__ import annotations

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

WIDTH = 1080
HEIGHT = 2400
SUPERSAMPLE = 2

# Restrained sage / clay / cream palette with warm wood.
WALL = (228, 216, 193)
WALL_DEEP = (199, 186, 163)
WALL_COOL = (206, 202, 186)
FLOOR = (151, 127, 103)
FLOOR_DEEP = (110, 92, 75)
WOOD = (146, 109, 72)
WOOD_DEEP = (104, 76, 50)
WOOD_WARM = (176, 133, 87)
WOOD_PALE = (198, 160, 114)
SAGE = (143, 161, 133)
SAGE_DEEP = (105, 124, 98)
SAGE_PALE = (183, 195, 172)
CLAY = (190, 124, 97)
CLAY_DEEP = (150, 92, 70)
CLAY_PALE = (214, 163, 134)
CREAM = (244, 235, 215)
CREAM_DEEP = (223, 210, 184)
DUST = (172, 166, 152)
DUST_DEEP = (139, 134, 122)
SHADOW = (72, 57, 46)
SKY = (178, 200, 199)
SKY_PALE = (211, 224, 219)
BRASS = (200, 162, 98)
GLASS = (156, 173, 172)
SUN = (255, 232, 186)


def rgb(color) -> np.ndarray:
    """Convert an 8-bit tuple to a linear-ish float triple in [0, 1]."""
    return np.asarray(color, dtype=np.float32) / 255.0


def blur(field: np.ndarray, radius: float) -> np.ndarray:
    """Gaussian blur a single-channel float field in [0, 1]."""
    if radius <= 0.0:
        return field
    image = Image.fromarray(
        (np.clip(field, 0.0, 1.0) * 255.0).astype(np.uint8), "L")
    image = image.filter(ImageFilter.GaussianBlur(radius))
    return np.asarray(image).astype(np.float32) / 255.0


def blur_rgb(canvas: np.ndarray, radius: float) -> np.ndarray:
    if radius <= 0.0:
        return canvas
    return np.stack(
        [blur(canvas[:, :, index], radius) for index in range(3)], axis=2)


def value_noise(height: int, width: int, cell: int, seed: int) -> np.ndarray:
    """Smooth deterministic value noise built from an upsampled random grid."""
    cell = max(2, int(cell))
    generator = np.random.default_rng(seed)
    grid_h = max(2, height // cell + 2)
    grid_w = max(2, width // cell + 2)
    grid = generator.random((grid_h, grid_w)).astype(np.float32)
    image = Image.fromarray((grid * 255.0).astype(np.uint8), "L")
    image = image.resize((width, height), Image.BICUBIC)
    return np.asarray(image).astype(np.float32) / 255.0


def fbm(
    height: int,
    width: int,
    cell: int,
    octaves: int,
    seed: int,
    gain: float = 0.5,
) -> np.ndarray:
    """Fractal sum of value noise, normalized to roughly [0, 1]."""
    total = np.zeros((height, width), dtype=np.float32)
    weight = 0.0
    amplitude = 1.0
    current = cell
    for index in range(octaves):
        total += amplitude * value_noise(
            height, width, current, seed + index * 131)
        weight += amplitude
        amplitude *= gain
        current = max(2, current // 2)
    return total / max(weight, 1e-6)


def rasterize(draw_call) -> np.ndarray:
    """Rasterize a PIL drawing call at 2x and downsample to a soft mask."""
    image = Image.new("L", (WIDTH * SUPERSAMPLE, HEIGHT * SUPERSAMPLE), 0)
    draw = ImageDraw.Draw(image)
    draw_call(draw, SUPERSAMPLE)
    image = image.resize((WIDTH, HEIGHT), Image.LANCZOS)
    return np.asarray(image).astype(np.float32) / 255.0


def rounded_rect_mask(
    x0: float,
    y0: float,
    x1: float,
    y1: float,
    radius: float = 0.0,
) -> np.ndarray:
    def draw_call(draw, scale):
        box = (x0 * scale, y0 * scale, x1 * scale, y1 * scale)
        if radius > 0.0:
            draw.rounded_rectangle(box, radius=radius * scale, fill=255)
        else:
            draw.rectangle(box, fill=255)

    return rasterize(draw_call)


def ellipse_mask(
    x0: float, y0: float, x1: float, y1: float) -> np.ndarray:
    def draw_call(draw, scale):
        draw.ellipse(
            (x0 * scale, y0 * scale, x1 * scale, y1 * scale), fill=255)

    return rasterize(draw_call)


def polygon_mask(points) -> np.ndarray:
    def draw_call(draw, scale):
        draw.polygon([(x * scale, y * scale) for x, y in points], fill=255)

    return rasterize(draw_call)


def line_mask(points, width: float) -> np.ndarray:
    def draw_call(draw, scale):
        draw.line(
            [(x * scale, y * scale) for x, y in points],
            fill=255,
            width=max(1, int(round(width * scale))),
            joint="curve")

    return rasterize(draw_call)


def hand_cut(mask: np.ndarray, seed: int, jitter: float = 0.055,
             cell: int = 18, hardness: float = 9.0) -> np.ndarray:
    """Give a mask the slightly irregular edge of a torn/painted paper shape."""
    softened = blur(mask, 1.4)
    wobble = fbm(HEIGHT, WIDTH, cell, 3, seed) - 0.5
    edged = (softened - 0.5) * hardness + wobble * jitter * hardness * 2.0
    return np.clip(edged + 0.5, 0.0, 1.0)


def gouache(
    color,
    seed: int,
    mottle: float = 0.075,
    cell: int = 96,
    grain: float = 0.028,
) -> np.ndarray:
    """A flat colour broken up by the pooling and grain of gouache paint."""
    base = rgb(color)
    pools = fbm(HEIGHT, WIDTH, cell, 4, seed) - 0.5
    speckle = fbm(HEIGHT, WIDTH, max(4, cell // 12), 3, seed + 7717) - 0.5
    value = 1.0 + pools * 2.0 * mottle
    canvas = base[None, None, :] * value[:, :, None]
    canvas = canvas + speckle[:, :, None] * grain
    return np.clip(canvas, 0.0, 1.0)


def wood_grain(
    color,
    seed: int,
    horizontal: bool = True,
    strength: float = 0.11,
) -> np.ndarray:
    """Warm wood with stretched directional grain."""
    if horizontal:
        rings = fbm(HEIGHT, 24, 6, 4, seed)
        rings = np.asarray(
            Image.fromarray((rings * 255.0).astype(np.uint8), "L").resize(
                (WIDTH, HEIGHT), Image.BICUBIC)).astype(np.float32) / 255.0
    else:
        rings = fbm(24, WIDTH, 6, 4, seed)
        rings = np.asarray(
            Image.fromarray((rings * 255.0).astype(np.uint8), "L").resize(
                (WIDTH, HEIGHT), Image.BICUBIC)).astype(np.float32) / 255.0
    ripple = np.sin(rings * 26.0) * 0.5 + 0.5
    base = gouache(color, seed + 31, mottle=0.05, cell=140)
    modulation = 1.0 + (ripple - 0.5) * 2.0 * strength
    return np.clip(base * modulation[:, :, None], 0.0, 1.0)


def shift(field: np.ndarray, dx: int, dy: int) -> np.ndarray:
    out = np.zeros_like(field)
    height, width = field.shape[:2]
    sx0, sx1 = max(0, -dx), min(width, width - dx)
    dx0, dx1 = max(0, dx), min(width, width + dx)
    sy0, sy1 = max(0, -dy), min(height, height - dy)
    dy0, dy1 = max(0, dy), min(height, height + dy)
    if sx1 <= sx0 or sy1 <= sy0:
        return out
    out[dy0:dy1, dx0:dx1] = field[sy0:sy1, sx0:sx1]
    return out


def over(canvas: np.ndarray, mask: np.ndarray, paint: np.ndarray) -> None:
    alpha = mask[:, :, None]
    canvas *= 1.0 - alpha
    canvas += paint * alpha


def tint(canvas: np.ndarray, mask: np.ndarray, color, strength: float) -> None:
    alpha = (mask * strength)[:, :, None]
    canvas *= 1.0 - alpha
    canvas += rgb(color)[None, None, :] * alpha


def cast_shadow(
    canvas: np.ndarray,
    mask: np.ndarray,
    dx: int = 7,
    dy: int = 12,
    radius: float = 16.0,
    strength: float = 0.30,
    color=SHADOW,
) -> None:
    """The soft contact shadow that sells the cut-paper diorama depth."""
    dropped = blur(shift(mask, dx, dy), radius)
    tint(canvas, dropped, color, strength)


def paper_lip(
    canvas: np.ndarray,
    mask: np.ndarray,
    dx: int = -4,
    dy: int = -5,
    strength: float = 0.42,
    color=CREAM,
) -> None:
    """A pale sliver on the light-facing edge, like the cut edge of card."""
    inner = shift(mask, -dx, -dy)
    lip = np.clip(mask - inner, 0.0, 1.0)
    lip = blur(lip, 1.1) * mask
    tint(canvas, lip, color, strength)


def form_shade(
    canvas: np.ndarray,
    mask: np.ndarray,
    strength: float = 0.24,
    radius: float = 26.0,
    color=SHADOW,
) -> None:
    """Darken the lower-right interior of a shape to give it volume."""
    inner = blur(shift(mask, -9, -12), radius)
    core = np.clip(mask - inner, 0.0, 1.0) * mask
    tint(canvas, core, color, strength)


def top_light(
    canvas: np.ndarray,
    mask: np.ndarray,
    strength: float = 0.20,
    radius: float = 22.0,
    color=SUN,
) -> None:
    inner = blur(shift(mask, 8, 11), radius)
    core = np.clip(mask - inner, 0.0, 1.0) * mask
    tint(canvas, core, color, strength)


def place(
    canvas: np.ndarray,
    mask: np.ndarray,
    paint: np.ndarray,
    shadow: bool = True,
    lip: bool = True,
    shade: bool = True,
    highlight: bool = False,
    shadow_dx: int = 7,
    shadow_dy: int = 12,
    shadow_radius: float = 16.0,
    shadow_strength: float = 0.30,
    shade_strength: float = 0.24,
    lip_strength: float = 0.42,
) -> None:
    """Composite one painted paper element with its diorama lighting."""
    if shadow:
        cast_shadow(
            canvas, mask, shadow_dx, shadow_dy, shadow_radius,
            shadow_strength)
    over(canvas, mask, paint)
    if shade:
        form_shade(canvas, mask, shade_strength)
    if highlight:
        top_light(canvas, mask)
    if lip:
        paper_lip(canvas, mask, strength=lip_strength)


def vertical_gradient(top, bottom) -> np.ndarray:
    ramp = np.linspace(0.0, 1.0, HEIGHT, dtype=np.float32)[:, None, None]
    return rgb(top)[None, None, :] * (1.0 - ramp) + rgb(bottom)[None, None, :] * ramp


def paper_finish(canvas: np.ndarray, seed: int = 4242) -> np.ndarray:
    """Deterministic paper tooth applied identically at every pixel position.

    Because the field is a pure function of position, every render of the room
    receives the same grain, so zone crops stay perfectly aligned with the
    master.
    """
    tooth = fbm(HEIGHT, WIDTH, 6, 4, seed)
    fibre = fbm(HEIGHT, WIDTH, 3, 2, seed + 913)
    modulation = 1.0 + (tooth - 0.5) * 0.070 + (fibre - 0.5) * 0.034
    finished = canvas * modulation[:, :, None]

    # Very soft warm bloom so the gouache reads as painted, not vector art.
    bloom = blur_rgb(finished, 9.0)
    finished = finished * 0.90 + bloom * 0.10
    return np.clip(finished, 0.0, 1.0)


def to_image(canvas: np.ndarray) -> Image.Image:
    return Image.fromarray(
        (np.clip(canvas, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8), "RGB")
